# Generated by Django 3.2.7 on 2022-01-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0002_teacher_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
