# Generated by Django 3.2.7 on 2022-01-10 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0004_alter_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='standrd_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageapp.standard'),
        ),
    ]
