# Generated by Django 3.2.7 on 2022-01-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
